server:
  port: 8080
logging:
  level:
    org.springframework.security: trace

keycloak:
  url: http://localhost:8080/auth
  realm: test

spring:
  security:
    oauth2:
      client:
        registration:
          test:
            client-id: test-app
            client-secret: a0fe1b28-02f1-4751-a4eb-a72f78882a47
            client-name: some client
            provider: keycloak
            scope: openid, profile
            redirect-uri-template: '{baseUrl}/login/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            token-uri: ${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/token
            authorization-uri: ${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/auth
            user-info-uri: ${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/certs
            user-name-attribute: preferred_username
